### PR TITLE
clean up(?) Mukundamala

### PR DESCRIPTION
**Pull request by shreevatsa**
(There are two versions on GRETIL; this is one of them.)

- ~~I was not able to get the dev server set up locally, so this is not tested and may need further work.~~ Tested locally, see below.
- I took the liberty of splitting 2 lines into 4 lines. Some book may have printed super-long verses in two lines but it's just too hard to read. Sometimes this required inserting a hyphen, and sometimes breaking at a consonant (like "…svādinām / asmākaṃ…). Should be fine IMO.
- ~~The verse numbers after 10 need restoring I guess. Will do if the rest of it looks good.~~ Verse numbers restored.

### CODE REVIEW

**Comment by shreevatsa** [comment]
It works!

image

**Comment by shreevatsa** [comment]
Companion commit (should I send a PR for it?): 
 ~~https://github.com/shreevatsa/ambuda/commit/51dd94e7acfd3741ae986f4a380414331f1b31c4~~ https://github.com/shreevatsa/ambuda/commit/611219bf9a691b66d71d09ac1d04e7436f59549b

**Comment by akprasad** [comment]
Wonderful -- thanks!

> I took the liberty of splitting 2 lines into 4 lines.

I prefer extremely high fidelity to the source text. But happily, the source text generally has the same idea as you!

https://archive.org/details/Kavyamala_anthology_series_of_Nirnaya_sagar_press/KavyamalaAnthologyVol.01-MahaganapatistotraOfRaghavachaitanyaEtc1929/page/n13/mode/2up

Let me know if you disagree., but I prefer the following verses to be 2-line since that's what's in the source text: 4, 7, 8, 14, 15, 20-24, 33

**Comment by shreevatsa** [comment]
1. Great that you found the printed book! We should probably link to it somewhere...

2. Done, changed verses 3, 7, 8, 21, 22, 24, 31, 33 to be 2-line as in the printed book. (Verses 4, 14, 15, 20 were already 2-line, and verse 23 is 4 lines in the printed book too.) Also restored the suboptimal-but- apparently-preferred-by-traditionalists split in verse 19, 22. I've left two spaces in the source text for convenience if we decide to mark this up someday (is there something under `<l>`?), but in the meantime XML treats multiple spaces as a single one so it shouldn't affecting anything. Also noticed a typo and fixed it. Worth trying to upstream such fixes to GRETIL but they're not very responsive.

General comments:

> I prefer extremely high fidelity to the source text. 

I agree that fidelity to a specific print version of a text is indeed reasonable to store in some form (so that the information is not lost), but

- things like variations between multiple printings (not counting entirely separate editions) of the same text, and obvious typos in the text, may require making a different choice in some places (I imagine there are TEI ways of encoding all these facts though!)
- part of the mission of making Sanskrit literature radically accessible IMO includes making the text more readable: inserting spaces, punctuation, indicating metrical breaks (like here breaking into 4 pādās), etc: presenting the "best" edition of the text rather than what someone happened to print at some point. Eventually I imagine we should have ways of marking up such "improvements" and making them user-configurable so that users can individually turn things on and off and see exactly what was printed if that's what they desire... right now there's a tradeoff between preserving the source information and making the text readable, but I guess it makes sense to preserve the printed version for now and automate readability later...

**Comment by akprasad** [comment]
> is there something under `<l>`?),

I've seen `<seg type="pada>` -- `<seg>` is the generic component for this, I believe.

Not sure about variant printings, but:

> obvious typos in the text

Yes, it's the extremely verbose `<choice><sic>tpyo</sic><corr>typo</corr></choice>`. You can see why I don't want proofers to write TEI.

> I guess it makes sense to preserve the printed version for now and automate readability later...

Yeah, I'm confident that if we have structured machine-readable text and parse data, we can slice the presented text however we want. I'm comfortable going very conservative on the transcription precisely because I'm confident that we will have incredible flexibility later.

**Comment by akprasad** [comment]
Oh, one thing I changed is that we no longer need the wrapping `<div>` for texts with a single "section." This fix is why I could add the चौरपञ्चाशिका earlier. So, just delete those and we can merge this in!

**Comment by shreevatsa** [comment]
Removed the wrapping `<div>`, and tested with the [companion commit](https://github.com/shreevatsa/ambuda/commit/611219bf9a691b66d71d09ac1d04e7436f59549b).

**Comment by akprasad** [comment]
Great! Let's merge it in

**Comment by akprasad** [comment]
@shreevatsa feel free to send me a PR for the companion commit

**Pull request merged**
