### PR TITLE
Cleanup gitagovinda

### PR DESCRIPTION
**Pull request by kiranlakkur**
Following changes have been made:
- Added 12 sections to each sarga
- Added trailer to each section
- Added 1p1 tags
- Corrected xml ids of each verse from GG_x.x to GG.x.x

### CODE REVIEW

**Comment by akprasad** [comment]
Amazing! As with the other text, please add a short respStmt and we're good to go!

**Comment by kiranlakkur** [comment]
I have now added respStmt.

**Comment by akprasad** [comment]
hmm -- sorry, one last thing. What do you mean by `Added 1p1 tags` ? If it's for the `<p>` tags that follow the `<head>` (e.g. <p>sāmodadāmodaraḥ</p>), can you make these `<head>` tags instead? I think this is the correct convention for multi-part headings, which this seems to be.

https://tei-c.org/release/doc/tei-p5-doc/en/html/DS.html#DSHD

So maybe:

```
+<head type="main">prathamaḥ sargaḥ</head>
+<head type="sub">sāmodadāmodaraḥ</head>

```

**Comment by akprasad** [comment]
Almost there! Let's use `header type="main"` and `header type="sub"` so that we can render these differently on the website.

**Comment by kiranlakkur** [comment]
Done now.

There are other `p` tags which are as such:

```
<p>|| mālavarāgeṇa gīyate || gītam 1 ||</p>
<p>|| gurjarīrāgeṇa gīyate || gītam 2 ||</p>
<p>|| vasantarāgeṇa gīyate || gītam 3 ||</p>
<p>|| rāmakarīrāgeṇa gīyate || gītam 4 ||</p>
<p>|| gurjarīrāgeṇa gīyate || gītam 5 ||</p>
<p>|| mālavarāgeṇa gīyate || gītam 6 ||</p>
<p>|| gurjarīrāgeṇa gīyate || gītam 7 ||</p>
<p>|| karṇāṭarāgeṇa gīyate|| gītam 8 ||</p>
<p>|| deśākhyarāgeṇa gīyate || gītam 9 ||</p>
<p>|| deśavarāḍīrāgeṇa gīyate || gītam 10 ||</p>
<p>|| gurjarīrāgeṇa gīyate || gītam 11 ||</p>
<p>|| naṭarāgeṇa gīyate || gītam 12 ||</p>
<p>|| mālavarāgeṇa gīyate || gītam 13 ||</p>
<p>|| vasantarāgeṇa gīyate || gītam 14 ||</p>
<p>|| gurjarīrāgeṇa gīyate || gītam 15 ||</p>
<p>|| deśākhyarāgeṇa gīyate || gītam 16 ||</p>
<p>|| bhairavīrāgeṇa gīyate || gītam 17 ||</p>
<p>|| gurjarīrāgeṇa gīyate || gītam 18 ||</p>
<p>|| deśavarāḍīrāgeṇa gīyate || gītam 19 ||</p>
<p>|| vasantarāgeṇa gīyate || gītam 20 ||</p>
<p>|| varāḍīrāgeṇa gīyate || gītam 21 ||</p>
<p>|| varāḍīrāgeṇa gīyate || gītam 22 ||</p>
<p>|| vibhāsarāgeṇa gīyate || gītam 23 ||</p>
<p>|| rāmakarīrāgeṇa gīyate || gītam 24 ||</p>
```

**Comment by akprasad** [comment]
I'm not sure how to render these. For now we can leave them as `<p>` and we can return to them later.

**Pull request merged**
